# action.yml
name: 'Hub'
description: 'go hub'

on:
  push:
    jobs:
      build:
        runs-on: golang:1.16.6-alpine3.14
        steps:
          - run: go build .
          - run: ./protobuf/build.sh

  pull_request:
    jobs:
      draft-release:
        runs-on: golang:1.16.6-alpine3.14
        using: python:3.8.11-alpine3.14
          steps:
              - run: python3 scripts/version.py current --commit # creates a draft release

  push:
    branches:
      - master
  jobs:
    full-release:
      runs-on: golang:1.16.6-alpine3.14
        using: python:3.8.11-alpine3.14
          steps:
              - run: python3 scripts/version.py current --commit --commit ---commit

