name: 'Build Hub'

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.5
      - run: go get google.golang.org/protobuf/cmd/protoc-gen-python google.golang.org/grpc/cmd/protoc-gen-python-grpc
      - run: go build .
      - run: ./protobuf/build.sh
