# draft-release.yml
name: "draft-release"
on:
  pull_request:
jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.5
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: pip install grpcio grpcio-tools
      - run: go get github.com/golang/protobuf/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - run: python3 scripts/version.py current --commit # creates a draft release
