name: "full-release"
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: golang:1.16.6-alpine3.14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: python3 scripts/version.py current --commit --commit --commit